Changes od python_check

diff --git a/.github/workflows/python_check.yml b/.github/workflows/python_check.yml
--- a/.github/workflows/python_check.yml
+++ b/.github/workflows/python_check.yml
@@ -21,20 +21,10 @@ jobs:
       with:
         python-version: "3.10"
 
-    - name: Cache pip
-      uses: actions/cache@v3
-      with:
-        path: ~/.cache/pip
-        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
-        restore-keys: |
-          ${{ runner.os }}-pip-
-
-
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-
 
   linting:
     runs-on: ubuntu-latest
@@ -52,18 +42,20 @@ jobs:
       run: |
         pip install flake8 pylint black
 
-    # Linting steps
+    # Linting with Flake8
     - name: Lint with flake8
       run: |
-        flake8 -v lit_ecology_classifier/**/*.py --count --select=E9,F7,F82 --show-source --statistics
-        
+        flake8 -v lit_ecology_classifier/**/*.py --count --select=E9,F7,F82 --show-source --statistics || echo "Flake8 found issues"
+
+    # Linting with Pylint
     - name: Lint with pylint
       run: |
-        pylint lit_ecology_classifier/**/*.py
+        pylint lit_ecology_classifier/**/*.py || echo "Pylint found issues"
 
+    # Check coding style with Black
     - name: Check coding style with Black
       run: |
-        black lit_ecology_classifier/**/*.py --check --diff 
+        black lit_ecology_classifier/**/*.py --check --diff || echo "Black formatting found issues"
 
   unit_tests:
     runs-on: ubuntu-latest
@@ -85,3 +77,17 @@ jobs:
     - name: Run unit tests
       run: |
         pytest --cov=lit_ecology_classifier
+
+  # Conditional Linting Failure Handling
+  linting_on_main:
+    if: github.ref == 'refs/heads/main'
+    runs-on: ubuntu-latest
+    needs: linting
+
+    steps:
+    - name: Ensure Linting Errors Cause Failure
+      run: |
+        if [ "$(echo ${{ steps.flake8.outcome }})" != "success" ]; then
+          echo "Linting issues detected on main, failing job."
+          exit 1
+        fi
